// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: api/welfare/welfare.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskKind int32

const (
	TaskKind_UNKNOWN             TaskKind = 0
	TaskKind_VIEW                TaskKind = 3
	TaskKind_ShardBook           TaskKind = 4
	TaskKind_DesktopStart        TaskKind = 5
	TaskKind_AddCalendarReminder TaskKind = 6
	TaskKind_SignSubscribe       TaskKind = 7
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "UNKNOWN",
		3: "VIEW",
		4: "ShardBook",
		5: "DesktopStart",
		6: "AddCalendarReminder",
		7: "SignSubscribe",
	}
	TaskKind_value = map[string]int32{
		"UNKNOWN":             0,
		"VIEW":                3,
		"ShardBook":           4,
		"DesktopStart":        5,
		"AddCalendarReminder": 6,
		"SignSubscribe":       7,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_welfare_welfare_proto_enumTypes[0].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_api_welfare_welfare_proto_enumTypes[0]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{0}
}

type GetTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     uint32      `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Project    string      `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	UserStatus *UserStatus `protobuf:"bytes,3,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskReq) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskReq) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetTaskReq) GetUserStatus() *UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return nil
}

type UserStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IsLogin bool   `protobuf:"varint,2,opt,name=is_login,json=isLogin,proto3" json:"is_login,omitempty"`
}

func (x *UserStatus) Reset() {
	*x = UserStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatus) ProtoMessage() {}

func (x *UserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatus.ProtoReflect.Descriptor instead.
func (*UserStatus) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatus) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserStatus) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

type GetTaskListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project    string      `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	UserStatus *UserStatus `protobuf:"bytes,2,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
}

func (x *GetTaskListReq) Reset() {
	*x = GetTaskListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListReq) ProtoMessage() {}

func (x *GetTaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListReq.ProtoReflect.Descriptor instead.
func (*GetTaskListReq) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskListReq) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetTaskListReq) GetUserStatus() *UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return nil
}

type GetTaskListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *GetTaskListResp) Reset() {
	*x = GetTaskListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListResp) ProtoMessage() {}

func (x *GetTaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListResp.ProtoReflect.Descriptor instead.
func (*GetTaskListResp) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskListResp) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 任务key recharge, buy_chapter, view_reader, read_new_book, view_classify, add_desktop, login
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 标题
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 描述
	Desc string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	// 任务场景：0 每日任务 1 成长任务 2 新手任务
	Kind int32 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// 是否展示进度条
	ShowProcess bool `protobuf:"varint,7,opt,name=show_process,json=showProcess,proto3" json:"show_process,omitempty"`
	// 总进度
	TotalProcess int32 `protobuf:"varint,8,opt,name=total_process,json=totalProcess,proto3" json:"total_process,omitempty"`
	// 奖励类型 0:金币 1:vip
	RewardType int32 `protobuf:"varint,9,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	// 奖励数量
	RewardNum int32 `protobuf:"varint,10,opt,name=reward_num,json=rewardNum,proto3" json:"reward_num,omitempty"`
	// 按钮链接
	ButtonJumpLink string          `protobuf:"bytes,11,opt,name=button_jump_link,json=buttonJumpLink,proto3" json:"button_jump_link,omitempty"`
	Completion     *TaskCompletion `protobuf:"bytes,12,opt,name=completion,proto3" json:"completion,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Task) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Task) GetShowProcess() bool {
	if x != nil {
		return x.ShowProcess
	}
	return false
}

func (x *Task) GetTotalProcess() int32 {
	if x != nil {
		return x.TotalProcess
	}
	return 0
}

func (x *Task) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *Task) GetRewardNum() int32 {
	if x != nil {
		return x.RewardNum
	}
	return 0
}

func (x *Task) GetButtonJumpLink() string {
	if x != nil {
		return x.ButtonJumpLink
	}
	return ""
}

func (x *Task) GetCompletion() *TaskCompletion {
	if x != nil {
		return x.Completion
	}
	return nil
}

type TaskCompletion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 展示进度条时，进度条的百分值
	Process int32 `protobuf:"varint,6,opt,name=process,proto3" json:"process,omitempty"`
	// 任务状态 0:未完成 1:已完成 2:已领取
	Status uint32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TaskCompletion) Reset() {
	*x = TaskCompletion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletion) ProtoMessage() {}

func (x *TaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletion.ProtoReflect.Descriptor instead.
func (*TaskCompletion) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{5}
}

func (x *TaskCompletion) GetProcess() int32 {
	if x != nil {
		return x.Process
	}
	return 0
}

func (x *TaskCompletion) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReportTaskCompletionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    TaskKind `protobuf:"varint,1,opt,name=kind,proto3,enum=welfare.v1.TaskKind" json:"kind,omitempty"`
	Uid     string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Project string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// 详情数据
	Kvs map[string]string `protobuf:"bytes,4,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // eg. {"action":"a", "page":"reader"}
}

func (x *ReportTaskCompletionReq) Reset() {
	*x = ReportTaskCompletionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTaskCompletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskCompletionReq) ProtoMessage() {}

func (x *ReportTaskCompletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskCompletionReq.ProtoReflect.Descriptor instead.
func (*ReportTaskCompletionReq) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{6}
}

func (x *ReportTaskCompletionReq) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_UNKNOWN
}

func (x *ReportTaskCompletionReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReportTaskCompletionReq) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ReportTaskCompletionReq) GetKvs() map[string]string {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type ReportTaskCompletionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportTaskCompletionResp) Reset() {
	*x = ReportTaskCompletionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTaskCompletionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskCompletionResp) ProtoMessage() {}

func (x *ReportTaskCompletionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskCompletionResp.ProtoReflect.Descriptor instead.
func (*ReportTaskCompletionResp) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{7}
}

type ReceiveTaskRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TaskId     int32       `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Project    string      `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	UserStatus *UserStatus `protobuf:"bytes,4,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
}

func (x *ReceiveTaskRewardReq) Reset() {
	*x = ReceiveTaskRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveTaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTaskRewardReq) ProtoMessage() {}

func (x *ReceiveTaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTaskRewardReq.ProtoReflect.Descriptor instead.
func (*ReceiveTaskRewardReq) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{8}
}

func (x *ReceiveTaskRewardReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReceiveTaskRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReceiveTaskRewardReq) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ReceiveTaskRewardReq) GetUserStatus() *UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return nil
}

type ReceiveTaskRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *ReceiveTaskRewardResp) Reset() {
	*x = ReceiveTaskRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveTaskRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTaskRewardResp) ProtoMessage() {}

func (x *ReceiveTaskRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTaskRewardResp.ProtoReflect.Descriptor instead.
func (*ReceiveTaskRewardResp) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveTaskRewardResp) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetSignInStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` // 用户id
}

func (x *GetSignInStateReq) Reset() {
	*x = GetSignInStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInStateReq) ProtoMessage() {}

func (x *GetSignInStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInStateReq.ProtoReflect.Descriptor instead.
func (*GetSignInStateReq) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{10}
}

func (x *GetSignInStateReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetSignInStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 今日已经签到
	TodaySigned bool `protobuf:"varint,1,opt,name=today_signed,json=todaySigned,proto3" json:"today_signed,omitempty"`
	// 连续签到天数
	ConsecutiveNo int32 `protobuf:"varint,2,opt,name=consecutive_no,json=consecutiveNo,proto3" json:"consecutive_no,omitempty"`
	// 最后签到时间
	LastTimeUnix int64 `protobuf:"varint,3,opt,name=last_time_unix,json=lastTimeUnix,proto3" json:"last_time_unix,omitempty"`
	// 最后获币
	LastCoin int32 `protobuf:"varint,4,opt,name=last_coin,json=lastCoin,proto3" json:"last_coin,omitempty"`
	// 下一次的连续签到天数
	NextConsecutiveNo int32 `protobuf:"varint,5,opt,name=next_consecutive_no,json=nextConsecutiveNo,proto3" json:"next_consecutive_no,omitempty"`
	// 下一次获币数量
	NextCoin int32 `protobuf:"varint,6,opt,name=next_coin,json=nextCoin,proto3" json:"next_coin,omitempty"`
}

func (x *GetSignInStateResp) Reset() {
	*x = GetSignInStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_welfare_welfare_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInStateResp) ProtoMessage() {}

func (x *GetSignInStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_welfare_welfare_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInStateResp.ProtoReflect.Descriptor instead.
func (*GetSignInStateResp) Descriptor() ([]byte, []int) {
	return file_api_welfare_welfare_proto_rawDescGZIP(), []int{11}
}

func (x *GetSignInStateResp) GetTodaySigned() bool {
	if x != nil {
		return x.TodaySigned
	}
	return false
}

func (x *GetSignInStateResp) GetConsecutiveNo() int32 {
	if x != nil {
		return x.ConsecutiveNo
	}
	return 0
}

func (x *GetSignInStateResp) GetLastTimeUnix() int64 {
	if x != nil {
		return x.LastTimeUnix
	}
	return 0
}

func (x *GetSignInStateResp) GetLastCoin() int32 {
	if x != nil {
		return x.LastCoin
	}
	return 0
}

func (x *GetSignInStateResp) GetNextConsecutiveNo() int32 {
	if x != nil {
		return x.NextConsecutiveNo
	}
	return 0
}

func (x *GetSignInStateResp) GetNextCoin() int32 {
	if x != nil {
		return x.NextCoin
	}
	return 0
}

var File_api_welfare_welfare_proto protoreflect.FileDescriptor

var file_api_welfare_welfare_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2f, 0x77, 0x65,
	0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x77, 0x65, 0x6c,
	0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x78, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x39, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x63, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0xd2, 0x02, 0x0a,
	0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x62,
	0x75, 0x74, 0x74, 0x6f, 0x6e, 0x5f, 0x6a, 0x75, 0x6d, 0x70, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x4a, 0x75, 0x6d,
	0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x65, 0x6c, 0x66,
	0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x42, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe7, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x28, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3e, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x4b, 0x76, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x4b, 0x76, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x1a, 0x0a, 0x18, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x94, 0x01, 0x0a, 0x14,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x30, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xee, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x12, 0x24, 0x0a, 0x0e,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e,
	0x69, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x2e, 0x0a, 0x13, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6e, 0x65,
	0x78, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x2a, 0x6e, 0x0a, 0x08,
	0x54, 0x61, 0x73, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x10, 0x04, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x05,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x69, 0x67,
	0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x10, 0x07, 0x32, 0x9e, 0x03, 0x0a,
	0x07, 0x57, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x65, 0x6c,
	0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x65, 0x6c, 0x66,
	0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1a, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e,
	0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x77, 0x65, 0x6c, 0x66,
	0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x5a, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x20, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x77, 0x65, 0x6c, 0x66, 0x61,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2a, 0x5a,
	0x28, 0x6e, 0x65, 0x77, 0x2d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x77, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_welfare_welfare_proto_rawDescOnce sync.Once
	file_api_welfare_welfare_proto_rawDescData = file_api_welfare_welfare_proto_rawDesc
)

func file_api_welfare_welfare_proto_rawDescGZIP() []byte {
	file_api_welfare_welfare_proto_rawDescOnce.Do(func() {
		file_api_welfare_welfare_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_welfare_welfare_proto_rawDescData)
	})
	return file_api_welfare_welfare_proto_rawDescData
}

var file_api_welfare_welfare_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_welfare_welfare_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_welfare_welfare_proto_goTypes = []interface{}{
	(TaskKind)(0),                    // 0: welfare.v1.TaskKind
	(*GetTaskReq)(nil),               // 1: welfare.v1.GetTaskReq
	(*UserStatus)(nil),               // 2: welfare.v1.UserStatus
	(*GetTaskListReq)(nil),           // 3: welfare.v1.GetTaskListReq
	(*GetTaskListResp)(nil),          // 4: welfare.v1.GetTaskListResp
	(*Task)(nil),                     // 5: welfare.v1.Task
	(*TaskCompletion)(nil),           // 6: welfare.v1.TaskCompletion
	(*ReportTaskCompletionReq)(nil),  // 7: welfare.v1.ReportTaskCompletionReq
	(*ReportTaskCompletionResp)(nil), // 8: welfare.v1.ReportTaskCompletionResp
	(*ReceiveTaskRewardReq)(nil),     // 9: welfare.v1.ReceiveTaskRewardReq
	(*ReceiveTaskRewardResp)(nil),    // 10: welfare.v1.ReceiveTaskRewardResp
	(*GetSignInStateReq)(nil),        // 11: welfare.v1.GetSignInStateReq
	(*GetSignInStateResp)(nil),       // 12: welfare.v1.GetSignInStateResp
	nil,                              // 13: welfare.v1.ReportTaskCompletionReq.KvsEntry
}
var file_api_welfare_welfare_proto_depIdxs = []int32{
	2,  // 0: welfare.v1.GetTaskReq.user_status:type_name -> welfare.v1.UserStatus
	2,  // 1: welfare.v1.GetTaskListReq.user_status:type_name -> welfare.v1.UserStatus
	5,  // 2: welfare.v1.GetTaskListResp.tasks:type_name -> welfare.v1.Task
	6,  // 3: welfare.v1.Task.completion:type_name -> welfare.v1.TaskCompletion
	0,  // 4: welfare.v1.ReportTaskCompletionReq.kind:type_name -> welfare.v1.TaskKind
	13, // 5: welfare.v1.ReportTaskCompletionReq.kvs:type_name -> welfare.v1.ReportTaskCompletionReq.KvsEntry
	2,  // 6: welfare.v1.ReceiveTaskRewardReq.user_status:type_name -> welfare.v1.UserStatus
	11, // 7: welfare.v1.Welfare.GetSignInState:input_type -> welfare.v1.GetSignInStateReq
	1,  // 8: welfare.v1.Welfare.GetTask:input_type -> welfare.v1.GetTaskReq
	3,  // 9: welfare.v1.Welfare.GetTaskList:input_type -> welfare.v1.GetTaskListReq
	7,  // 10: welfare.v1.Welfare.ReportTaskCompletion:input_type -> welfare.v1.ReportTaskCompletionReq
	9,  // 11: welfare.v1.Welfare.ReceiveTaskReward:input_type -> welfare.v1.ReceiveTaskRewardReq
	12, // 12: welfare.v1.Welfare.GetSignInState:output_type -> welfare.v1.GetSignInStateResp
	5,  // 13: welfare.v1.Welfare.GetTask:output_type -> welfare.v1.Task
	4,  // 14: welfare.v1.Welfare.GetTaskList:output_type -> welfare.v1.GetTaskListResp
	8,  // 15: welfare.v1.Welfare.ReportTaskCompletion:output_type -> welfare.v1.ReportTaskCompletionResp
	10, // 16: welfare.v1.Welfare.ReceiveTaskReward:output_type -> welfare.v1.ReceiveTaskRewardResp
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_welfare_welfare_proto_init() }
func file_api_welfare_welfare_proto_init() {
	if File_api_welfare_welfare_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_welfare_welfare_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCompletion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTaskCompletionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTaskCompletionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveTaskRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveTaskRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_welfare_welfare_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_welfare_welfare_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_welfare_welfare_proto_goTypes,
		DependencyIndexes: file_api_welfare_welfare_proto_depIdxs,
		EnumInfos:         file_api_welfare_welfare_proto_enumTypes,
		MessageInfos:      file_api_welfare_welfare_proto_msgTypes,
	}.Build()
	File_api_welfare_welfare_proto = out.File
	file_api_welfare_welfare_proto_rawDesc = nil
	file_api_welfare_welfare_proto_goTypes = nil
	file_api_welfare_welfare_proto_depIdxs = nil
}
